"""Generate draft rubric (model answers + criteria + scores) from exam paper."""
import asyncio
import json
import re

import fitz
from google import genai
from google.genai import types


def _build_prompt(question_from: int, question_to: int, subject: str | None, school_level: str | None, grade: int | None) -> str:
    context_parts = []
    if school_level:
        level_map = {"elementary": "초등학교", "middle": "중학교", "high": "고등학교"}
        context_parts.append(level_map.get(school_level, school_level))
    if grade:
        context_parts.append(f"{grade}학년")
    if subject:
        context_parts.append(subject)
    context = " ".join(context_parts) if context_parts else "중학교"

    return f"""이 문서는 {context} 시험지입니다.

{question_from}번부터 {question_to}번 문항에 대한 채점기준표 초안을 작성해주세요.
하위 문항(예: 3-(1), 3-(2))도 각각 별도 항목으로 추출하세요.

각 문항마다 아래 정보를 생성하세요:
- number: 문항 번호 ("1", "2-1", "3-(1)" 등 원문 그대로)
- question_text: 해당 문항을 이해하는 데 필요한 지문+질문 전체
- max_score: 배점 (시험지에 표시된 경우 그대로, 없으면 합리적으로 추정)
- model_answer: 모범 답안 (정확하고 완전한 답)
- criteria: 세부 채점 기준 목록. 각 항목은 description(기준 설명)과 points(점수) 포함

채점 기준 작성 지침:
- 부분 점수 가능한 경우 항목을 나눠서 작성
- 오탈자/문법 감점 기준도 포함 (해당되는 경우)
- 인정답이 있으면 criteria에 명시

JSON 형식으로만 응답:
{{
  "questions": [
    {{
      "number": "1",
      "question_text": "지문 및 질문 텍스트",
      "max_score": 4,
      "model_answer": "모범 답안",
      "criteria": [
        {{"description": "핵심 내용 포함", "points": 2}},
        {{"description": "문법/철자 정확", "points": 2}}
      ]
    }}
  ]
}}"""


async def generate_rubric_from_paper(
    client: genai.Client,
    file_path: str,
    question_from: int,
    question_to: int,
    subject: str | None = None,
    school_level: str | None = None,
    grade: int | None = None,
) -> dict:
    """Returns {"questions": [...]} with model answers + criteria generated by Gemini."""
    doc = fitz.open(file_path)
    images = []
    for page in doc:
        mat = fitz.Matrix(2.0, 2.0)
        pix = page.get_pixmap(matrix=mat)
        images.append(pix.tobytes("png"))
    doc.close()

    parts = [types.Part.from_bytes(data=img, mime_type="image/png") for img in images]
    parts.append(types.Part.from_text(text=_build_prompt(question_from, question_to, subject, school_level, grade)))

    response = await asyncio.to_thread(
        client.models.generate_content,
        model="gemini-2.5-flash",
        contents=parts,
        config=types.GenerateContentConfig(response_mime_type="application/json"),
    )

    raw = response.text.strip()
    if raw.startswith("```"):
        raw = re.sub(r"^```[a-zA-Z]*\n?", "", raw)
        raw = re.sub(r"\n?```$", "", raw)
        raw = raw.strip()

    data = json.loads(raw)
    if "questions" not in data:
        data = {"questions": []}
    return data
