"""Generate draft rubric (model answers + criteria + scores) from exam paper."""
import asyncio
import json
import re

import fitz
from google import genai
from google.genai import types

from app.gemini.prompts import RUBRIC_GENERATE_DEFAULT, render, select_template


def _build_context(subject: str | None, school_level: str | None, grade: int | None) -> str:
    parts = []
    if school_level:
        level_map = {"elementary": "초등학교", "middle": "중학교", "high": "고등학교"}
        parts.append(level_map.get(school_level, school_level))
    if grade:
        parts.append(f"{grade}학년")
    if subject:
        parts.append(subject)
    return " ".join(parts) if parts else "중학교"


def _build_prompt(
    question_from: int,
    question_to: int,
    subject: str | None,
    school_level: str | None,
    grade: int | None,
    template_override: str | None = None,
) -> str:
    context = _build_context(subject, school_level, grade)
    template = select_template(template_override, RUBRIC_GENERATE_DEFAULT)
    return render(
        template, RUBRIC_GENERATE_DEFAULT,
        context=context,
        question_from=question_from,
        question_to=question_to,
    )


async def generate_rubric_from_paper(
    client: genai.Client,
    file_path: str,
    question_from: int,
    question_to: int,
    subject: str | None = None,
    school_level: str | None = None,
    grade: int | None = None,
    prompt_override: str | None = None,
) -> dict:
    """Returns {"questions": [...]} with model answers + criteria generated by Gemini."""
    doc = fitz.open(file_path)
    images = []
    for page in doc:
        mat = fitz.Matrix(2.0, 2.0)
        pix = page.get_pixmap(matrix=mat)
        images.append(pix.tobytes("png"))
    doc.close()

    parts = [types.Part.from_bytes(data=img, mime_type="image/png") for img in images]
    parts.append(types.Part.from_text(text=_build_prompt(
        question_from, question_to, subject, school_level, grade, prompt_override,
    )))

    response = await asyncio.to_thread(
        client.models.generate_content,
        model="gemini-2.5-flash",
        contents=parts,
        config=types.GenerateContentConfig(response_mime_type="application/json"),
    )

    raw = response.text.strip()
    if raw.startswith("```"):
        raw = re.sub(r"^```[a-zA-Z]*\n?", "", raw)
        raw = re.sub(r"\n?```$", "", raw)
        raw = raw.strip()

    data = json.loads(raw)
    if "questions" not in data:
        data = {"questions": []}
    return data
